### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by sannykr**
No change. Can you please merge to trigger the build for python 3.6

### CODE REVIEW

**Comment by jakirkham** [comment]
It needs to be [re-rendered]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ). Please make sure to use `conda` 4.3.22 as well.

**Comment by mwcraig** [comment]
@sannykr -- you need to re-erender the feedstock to add python 3.6

To do that, first: `conda install -c conda-forge conda-smithy` and then follow the instructions here: https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock

**Comment by sannykr** [comment]
@mwcraig : I tried to rerender, but it's not successful. I am getting some error. This is what I got:
sannys-MacBook-Pro:pytest-django-feedstock sannykumar$ conda smithy rerender [--commit]
Traceback (most recent call last):
  File "/anaconda/bin/conda-smithy", line 4, in <module>
    import conda_smithy.cli
  File "/anaconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 14, in <module>
    from . import ci_register
  File "/anaconda/lib/python2.7/site-packages/conda_smithy/ci_register.py", line 10, in <module>
    from . import github
  File "/anaconda/lib/python2.7/site-packages/conda_smithy/github.py", line 16, in <module>
    from . import configure_feedstock
  File "/anaconda/lib/python2.7/site-packages/conda_smithy/configure_feedstock.py", line 48, in <module>
    from conda_build_all.version_matrix import special_case_version_matrix, filter_cases
  File "/anaconda/lib/python2.7/site-packages/conda_build_all/version_matrix.py", line 19, in <module>
    for attr in ['Unsatisfiable', 'NoPackagesFound'])
  File "/anaconda/lib/python2.7/site-packages/conda_build_all/version_matrix.py", line 19, in <genexpr>
    for attr in ['Unsatisfiable', 'NoPackagesFound'])
AttributeError: 'module' object has no attribute 'NoPackagesFound'

**Comment by sannykr** [comment]
@mwcraig : It worked finally after downgrading conda. I used this link: 
https://stackoverflow.com/questions/42552816/introduce-new-python-version-to-conda-forge-feedstock

**Comment by sannykr** [comment]
@mwcraig : Although I rerendered, it didn't build for python 36. Do I need to change the files manually?

**Comment by kwilcox** [comment]
The issue is that `setuptools_scm =1.11.1` isn't built for py3.6 so it is skipping 3.6. I'll see if I can bump `setuptools_scm` to 1.15.

**Comment by kwilcox** [comment]
@ocefpaf Do you remember this whole `setuptools_scm` non-sense? The build step is trying to download `setuptools_scm` from the `pytest-django/setup.py` file (`setup_requires=['setuptools_scm>=1.11.1']`) even though conda has installed it already.

```
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/setuptools_scm/
```

**Comment by ocefpaf** [comment]
@ocefpaf Do you remember this whole `setuptools_scm` non-sense?

To be honest no. I always have to "re-learn" that when updating things with `setuptools_scm`,

> The build step is trying to download `setuptools_scm` from the `pytest-django/setup.py` file (`setup_requires=['setuptools_scm>=1.11.1']`) even though conda has installed it already.

```
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/setuptools_scm/
```

Argh! Sometimes I took the "hammer" approach and patched the recipe to avoid `setuptools_scm`. I'll take a look later on what we can do here to avoid that.

**Comment by kwilcox** [comment]
@sannykr I appreciate the persistence. We are going to have to patch out the setuptools_scm stuff from the setup.py unless someone else has some brilliant way to fix this.

**Comment by sannykr** [comment]
@kwilcox : Will it fix the issue if we make it a noarch?

**Comment by isuruf** [comment]
@sannykr, you'll need this patch https://github.com/pytest-dev/pytest-django/pull/467/files

**Comment by kwilcox** [comment]
That is incorrect @isuruf. I have a fix and will make a PR soon.

**Comment by kwilcox** [comment]
https://github.com/conda-forge/pytest-django-feedstock/pull/11

**Pull request closed without merging**
